services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      # Mount the database file so data persists
      - ./projects.db:/app/projects.db
      # Optionally mount static files for easier development
      - ./static:/app/static
      - ./templates:/app/templates
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=production
    restart: unless-stopped
